"""A footage grade must not recolor later information layers."""
from pathlib import Path
import subprocess
import tempfile
import unittest

import numpy as np

from tests import test_visual_editing as fixtures
from video_harness.common import read
from video_harness.video_effects import _digest
from video_harness.visual_editing import render_visual_edit


class VisualGradeOrderTests(unittest.TestCase):
    def pixels(self,path):
        return np.frombuffer(subprocess.check_output(['ffmpeg','-v','error','-i',str(path),
            '-f','rawvideo','-pix_fmt','rgb24','-']),np.uint8).reshape(-1,128,128,3)

    def test_source_monochrome_keeps_later_title_green_and_audio_unchanged(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp);cfg,edl=fixtures.VisualEditingTests().fixture(root,source_audio=True)
            cfg.update(visual_pipeline_version=2,style='monochrome',style_intensity=1)
            baseline=render_visual_edit(cfg,edl,root/'baseline',preview=False)
            mapping=read(baseline/'frame-mapping.json')
            cfg['editing_pattern']={'id':'playful_short','music':'off','sfx':'off','beat_sync':'off'}
            from datetime import date
            from PIL import Image
            from video_harness.assets import register_asset
            image=root/'red-logo.png';Image.new('RGB',(40,40),'red').save(image)
            rights=root/'logo-rights.txt';rights.write_text('Synthetic colored image generated by this test.')
            asset=register_asset(image,{'asset_id':'logo','kind':'image','creator':'Test fixture',
                'source_url':'https://example.org/logo','license_url':'https://example.org/rights',
                'acquired_on':date.today().isoformat(),'verified_on':date.today().isoformat(),
                'evidence_path':str(rights),'credit':'Synthetic logo','cost':0,'currency':'JPY',
                'content_id':'none','owned_by_user':True,'ownership_evidence_path':str(rights),'rights':cfg['assets'][0]['rights']})
            cfg['assets'].append(asset)
            cfg['cue_plan']={'version':1,'mapping_sha256':_digest(mapping),'cues':[
                {'id':'red-information','asset_id':'logo','role':'image','output_start':0,'output_end':.8,'reason':'Fixture logo'}]}
            cfg['video_effects']={'version':1,'mapping_sha256':_digest(mapping),'events':[
                {'id':'green-information','type':'keyword_title','output_start':0,'output_end':.8,
                 'strength':1,'reason':'Synthetic information-color preservation',
                 'parameters':{'text':'A','foreground':'#00FF00','background':'#000000',
                               'font_size_fraction':.12}}]}
            out=render_visual_edit(cfg,edl,root/'title',preview=False)
            frames=self.pixels(out/'video.mp4')
            frame=frames[4].astype(int)
            green=(frame[:,:,1]>100)&(frame[:,:,1]>frame[:,:,0]+60)&(frame[:,:,1]>frame[:,:,2]+60)
            self.assertGreater(int(green.sum()),4)
            self.assertGreater(frame[45,45,0]-frame[45,45,1],100)
            legacy=render_visual_edit({**cfg,'visual_pipeline_version':1},edl,root/'legacy-title',preview=False)
            old_frame=self.pixels(legacy/'video.mp4')[4].astype(int)
            self.assertLess(np.ptp(old_frame[45,45]),5)
            self.assertFalse(((old_frame[:,:,1]>old_frame[:,:,0]+60)&(old_frame[:,:,1]>old_frame[:,:,2]+60)).any())
            # The footage in the top-left remains achromatic.
            self.assertLess(np.ptp(frame[5:20,5:20].mean(axis=(0,1))),5)
            def pcm(path):
                return subprocess.check_output(['ffmpeg','-v','error','-i',str(path),'-vn','-f','s16le','-'])
            self.assertEqual(pcm(baseline/'video.mp4'),pcm(out/'video.mp4'))
            evidence=read(out/'visual-pipeline.json')
            self.assertEqual(evidence['version'],2)
            self.assertEqual(evidence['grade_scope'],'assembled_footage_before_overlays_and_effects')
            self.assertTrue((out/'visual-graded.mp4').is_file())

    def test_legacy_composed_grade_is_explicit_and_invalid_versions_fail(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp);cfg,edl=fixtures.VisualEditingTests().fixture(root,source_audio=False)
            cfg.update(style='monochrome',style_intensity=1)
            old=render_visual_edit(cfg,edl,root/'old',preview=False)
            self.assertEqual(read(old/'visual-pipeline.json')['version'],1)
            self.assertFalse((old/'visual-graded.mp4').exists())
            for value in (True,0,3,'2'):
                with self.subTest(value=value),self.assertRaisesRegex(ValueError,'visual_pipeline_version'):
                    render_visual_edit({**cfg,'visual_pipeline_version':value},edl,root/f'invalid-{value}',preview=False)


if __name__=='__main__':
    unittest.main()
